#!/bin/bash
set -e

if [ "$1" == "clean" ]; then
  rm -rf build include lib 2>/dev/null 
  exit 0
fi

if [ ! -d "build" ]; then
  mkdir build
fi

cd build
# XXX - Hardcoded
cmake -DSENSEI_DIR=$1/lib/cmake/ \
  -DTBB_LIBRARY_DEBUG=/lus/grand/projects/visualization/mvictoras/argo/install/ospray/v2.4.0-glm-fix/tbb/lib/intel64/gcc4.8/libtbb_debug.so \
  -DTBB_LIBRARY_RELEASE=/lus/grand/projects/visualization/mvictoras/argo/install/ospray/v2.4.0-glm-fix/tbb/lib/intel64/gcc4.8/libtbb.so \
  ..
make install
